language: python
python: 3.7
install:
  - pip install pipenv
  - pipenv install --ignore-pipfile --deploy
script: bash build.sh
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $PERSONAL_TOKEN
  keep_history: true
  on:
    branch: master
