name: Publish docs
on:
  push:
    branches:
      - master
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Build docs
        run: |
          pip install pipenv
          pipenv install --ignore-pipfile --deploy
          pipenv run make html
      - name: Publish docs
        run: |
          git checkout gh-pages
          rm -f .git/index
          git clean -fdx -e _build
          mv _build/html/* ./
          rm -rf _build
          touch .nojekyll
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Automated doc generation"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
